name: Trigger Second Repo Workflow

on:
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print branch name
      run: echo "Current branch: ${{ github.ref_name }}"
