name: Trigger Second Repo Workflow

on:
  workflow_dispatch:
  workflow_call:
    inputs: 
      branch:
        type: string
        required: true
    
    secrets:
      GH_PAT:
        required: true
jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref || github.ref }}

      - name: Prints the current branch name
        run: git branch

      - name: Create a file
        run: echo "abc" >  test.txt

      - name: lis files
        run: ls -lrt

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: lis files
        run: ls -lrt

      - name: Prints the current branch name
        run: git branch
