name: Trigger Second Repo Workflow

on:
  workflow_dispatch:

jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prints the current branch name
        run: echo "${GITHUB_BRANCH##*/}"
        env:
          GITHUB_BRANCH: ${{ github.ref_name }}
