name: Trigger Second Repo Workflow

on:
  workflow_dispatch:
  workflow_call:
    inputs: 
      branch:
        type: string
        required: true
    
    secrets:
      GH_PAT:
        required: true
jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.branch }}

      - name: Prints the current branch name
        run: git branch
