name: Trigger Second Repo Workflow

on:
  workflow_dispatch:
  workflow_call:
    GH_PAT:
      required: true
jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prints the current branch name
        run: echo "${GITHUB_BRANCH##*/}"
